let products = [
    {
      img: "./images/Aimage.webp",
      name: "Lucky Bamboo Plant - 3 Layer",
      price: "399",
      category: "Houseplants",
    },
    {
      img: "./images/AtlantisPlanter-PastelBlue.webp",
      name: "Peace Lily Plant",
      price: "299",
      category: "Houseplants",
    },
    {
      img: "./images/AtlantisPlanter-PastelPink.webp",
      name: "Money Plant Golden",
      price: "299",
      category: "Houseplants",
    },
    {
      img: "./images/AtlantisPlanter-Teal_dc150664.webp",
      name: "Snake Plant - Golden Hahnii",
      price: "299",
      category: "Houseplants",
    },
    {
      img: "./images/AtlantisPlanter-Teal.webp",
      name: "Areca Palm Plant XL",
      price: "2499",
      category: "Houseplants",
    },
    {
      img: "./images/DSC_2431.webp",
      name: "Areca Palm Plant",
      price: "499",
      category: "Houseplants",
    },
    {
      img: "./images/LagosPlanter-Mocca.webp",
      name: "Syngonium Pink Plant",
      price: "249",
      category: "Houseplants",
    },
    {
      img: "./images/LagosPlanter-Grey.webp",
      name: "Jade Plant Mini",
      price: "249",
      category: "Houseplants",
    },
    {
      img: "./images/small-atlantis.webp",
      name: "Broken Heart Plant",
      price: "249",
      category: "Houseplants",
    },
    {
      img: "./images/SpiroCeramicPot-White.webp",
      name: "Bamboo Palm Plant",
      price: "399",
      category: "Houseplants",
    },
    {
      img: "./images/Venice12Planter-Black.webp",
      name: "Ficus Bonsai Plant",
      price: "799",
      category: "Houseplants",
    },
    {
      img: "./images/air-purifying-bundle.png",
      name: "Areca Palm, Sansevieria Futura Superba",
      price: "999",
      category: "Houseplant Sets",
    },
    {
      img: "./images/air-purifying-bundle.webp",
      name: "Syngonium Pink, Money N Joy",
      price: "999",
      category: "Houseplant Sets",
    },
    {
      img: "./images/sleep-better-bundle.webp",
      name: "The Sleep Better Bundle",
      price: "1299",
      category: "Houseplant Sets",
    },
    {
      img: "./images/rubber-variegated-and-aglaonema-pink.webp",
      name: "Rubber Variegated and Aglaonema Pink",
      price: "1199",
      category: "Houseplant Sets",
    },
    {
      img: "./images/zz-peace-lily.webp",
      name: "ZZ, Peace Lily",
      price: "999",
      category: "Houseplant Sets",
    },
    {
      img: "./images/living-room-bundle.webp",
      name: "The Living Room Bundle",
      price: "1299",
      category: "Houseplant Sets",
    },
    {
      img: "./images/tabletop-succulent-bundle.webp",
      name: "The Tabletop Succulent Bundle",
      price: "1599",
      category: "Houseplant Sets",
    },
    {
      img: "./images/low-maintenance-bundle.webp",
      name: "The Low Maintenance Bundle",
      price: "1299",
      category: "Houseplant Sets",
    },
    {
      img: "./images/sun-loving-succulent-bundle.webp",
      name: "The Sun-loving Succulent Bundle",
      price: "1499",
      category: "Houseplant Sets",
    },
    {
      img: "./images/4-inch-set-of-6-gardening-pots.webp",
      name: "The Sun-loving Succulent Bundle",
      price: "1499",
      category: "Flowerpot",
      subcategory: "Plastic Pots",
    },
    {
      img: "./images/small-white-stone-pebble.webp",
      name: "Pebble Planter",
      price: "599",
      category: "Flowerpot",
      subcategory: "Plastic Pots",
    },
    {
      img: "./images/7.5-inch-set-of-5-multi-1.webp",
      name: "Ugaoo Krish Self Watering Planter",
      price: "149",
      category: "Flowerpot",
      subcategory: "Plastic Pots",
    },
    {
      img: "./images/DSC_5784.webp",
      name: "Frosted Ceramic Pot",
      price: "599",
      category: "Flowerpot",
      subcategory: "Ceramic Pots",
    },
    {
      img: "./images/rose-red-apple-ceramic-pot.webp",
      name: "Apple Ceramic Pot",
      price: "799",
      category: "Flowerpot",
      subcategory: "Ceramic Pots",
    },
    {
      img: "./images/AImageWithPlant-2.webp",
      name: "Spiro Ceramic Pot",
      price: "399",
      category: "Flowerpot",
      subcategory: "Ceramic Pots",
    },
    {
      img: "./images/hanging-pyramids-planter.webp",
      name: "Hanging Pyramids Planter",
      price: "1799",
      category: "Flowerpot",
      subcategory: "Metallic Pots",
    },
    {
      img: "./images/white-nyx-planter.webp",
      name: "Nyx Planter",
      price: "349",
      category: "Flowerpot",
      subcategory: "Metallic Pots",
    },
    {
      img: "./images/dove-planter.webp",
      name: "Dove Planter",
      price: "1999",
      category: "Flowerpot",
      subcategory: "Metallic Pots",
    },
    {
      img: "./images/5-kg-garden-soil-mix.webp",
      name: "Garden Soil Mix",
      price: "349",
      category: "Soil",
    },
    {
      img: "./images/cocopeat-block.webp",
      name: "Cocopeat Block",
      price: "199",
      category: "Soil",
    },
    {
      img: "./images/cactus-succulent-potting-mix-5-kg.webp",
      name: "Cactus & Succulent Potting Mix - 5 kg",
      price: "499",
      category: "Soil",
    },
    {
      img: "./images/pot-o-mix-5-kg-potting-mix.webp",
      name: "Pot-O-Mix - 5 Kg Potting Mix",
      price: "399",
      category: "Soil",
    },
    {
      img: "./images/garden_red_soil.webp",
      name: "Garden Red Soil",
      price: "199",
      category: "Soil",
    },
    {
      img: "./images/5-kg-cow-manure.webp",
      name: "Cow Manure",
      price: "199",
      category: "Fertilizer",
    },
    {
      img: "./images/5-kg-vermicompost.webp",
      name: "Vermicompost",
      price: "199",
      category: "Fertilizer",
    },
    {
      img: "./images/organic-manure-1-kg.webp",
      name: "Organic Manure - 1 Kg",
      price: "199",
      category: "Fertilizer",
    },
    {
      img: "./images/perlite-250gm.webp",
      name: "Perlite - 250gm",
      price: "199",
      category: "Fertilizer",
    },
    {
      img: "./images/epsom-salt-1-kg.webp",
      name: "Epsom Salt - 1 kg",
      price: "199",
      category: "Fertilizer",
    },
    {
      img: "./images/plant-fertilizer-pellets-1-kg.webp",
      name: "Plant Fertilizer Pellets - 1 Kg",
      price: "299",
      category: "Fertilizer",
    },
    {
      img: "./images/organic-manure-1-kg.webp",
      name: "Organic Manure - 1 Kg",
      price: "199",
      category: "Fertilizer",
    },
    {
      img: "./images/Plant_Tonic.webp",
      name: "Seaweed Extract Fertilizer - Plant Tonic 250 ml",
      price: "299",
      category: "Fertilizer",
    },
    {
      img: "./images/Plant_Tonic.webp",
      name: "Seaweed Extract Fertilizer - Plant Tonic 100 ml",
      price: "199",
      category: "Fertilizer",
    },
  ];